spring:
  application:
    name: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: qwe123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mail
    password: tsei1234